### ISSUE TITLE
CSS errors in Chrome

### ISSUE THREAD

**Issue by aatmnv** [EIDSS/EIDSSDemo#1]
CSS style sheet is not working in Chrome

**Comment by aatmns** [comment]
I saw that error too.

**Comment by christhompson17** [comment]
Added tags

**Comment by aatmnv** [comment]
Work around is offered. Use Internet Explorer while our Dev Team is correcting CSS approach for Google Chrome and Mozilla Firefox browsers.
Bug is closed
