### ISSUE TITLE
Navigation menu position shifting

### ISSUE THREAD

**Issue by aatmns** [EIDSS/EIDSSDemo#3]
An issue.
User: Administrator
Section: Administration
Browser: Chrome
When Creating a new employee, Navigation menu is shifted down to end of the pages, making it invisible and not very useful. Suggesting to lock Navigation Menu to be constantly in the upper right hand corner, despite the size of the screen:
![position_of_label](https://user-images.githubusercontent.com/32458032/31122387-9d1a5152-a809-11e7-9f96-9cfd1ea63d9c.JPG)

**Comment by aatmnv** [comment]
This is an issue that needs to be discussed with our UX and Dev teams on keeping user interface consistent.
I will keep this thread informed about further development.

**Comment by aatmns** [comment]
Additionally I noticed that IE browser actually correctly keeps NavMenu at the right hand top corner. This is something you may want to consider. Anatoly

**Comment by aatmnv** [comment]
Our UX team has reviewed this comment and this is the industry standard approach to move NavMenu to the bottom to accommodate tablets and smartphone screens. Issue is closed.
